export const PERMISSION_CODES = {
  AUTH_LOGIN: "auth.login",
  AUTH_MANAGE: "auth.manage",
  CHURCHES_READ: "churches.read",
  CHURCHES_UPDATE: "churches.update",
  CHURCHES_MANAGE: "churches.manage",
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  USERS_MANAGE: "users.manage",
  STAGES_READ: "stages.read",
  STAGES_CREATE: "stages.create",
  STAGES_UPDATE: "stages.update",
  STAGES_DELETE: "stages.delete",
  CHILDREN_READ: "children.read",
  CHILDREN_CREATE: "children.create",
  CHILDREN_UPDATE: "children.update",
  CHILDREN_DELETE: "children.delete",
  CHILDREN_EXPORT: "children.export",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_CREATE: "attendance.create",
  ATTENDANCE_UPDATE: "attendance.update",
  ATTENDANCE_DELETE: "attendance.delete",
  ATTENDANCE_EXPORT: "attendance.export",
  FOLLOWUPS_READ: "followups.read",
  FOLLOWUPS_CREATE: "followups.create",
  FOLLOWUPS_UPDATE: "followups.update",
  FOLLOWUPS_DELETE: "followups.delete",
  EVENTS_READ: "events.read",
  EVENTS_CREATE: "events.create",
  EVENTS_UPDATE: "events.update",
  EVENTS_DELETE: "events.delete",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_CREATE: "notifications.create",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",
  DOCUMENTS_READ: "documents.read",
  DOCUMENTS_CREATE: "documents.create",
  DOCUMENTS_DELETE: "documents.delete",
  AI_USE: "ai.use",
  AI_MANAGE: "ai.manage",
  AUDIT_READ: "audit.read",
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const PERMISSION_LIST = Object.values(PERMISSION_CODES) as PermissionCode[];
