export const PERMISSION_CODES = {
  BENEFICIARIES_READ: "beneficiaries.read",
  BENEFICIARIES_CREATE: "beneficiaries.create",
  BENEFICIARIES_UPDATE: "beneficiaries.update",
  BENEFICIARIES_DELETE: "beneficiaries.delete",
  BENEFICIARIES_TRANSFER: "beneficiaries.transfer",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_CREATE: "attendance.create",
  ATTENDANCE_EXPORT: "attendance.export",
  FOLLOWUPS_READ: "followups.read",
  FOLLOWUPS_CREATE: "followups.create",
  FOLLOWUPS_UPDATE: "followups.update",
  FOLLOWUPS_DELETE: "followups.delete",
  SERVANTS_READ: "servants.read",
  SERVANTS_CREATE: "servants.create",
  SERVANTS_UPDATE: "servants.update",
  SERVANTS_DELETE: "servants.delete",
  SERVANTS_APPROVE: "servants.approve",
  SERVANTS_ASSIGN: "servants.assign",
  SERVICES_READ: "services.read",
  SERVICES_CREATE: "services.create",
  SERVICES_UPDATE: "services.update",
  SERVICES_DELETE: "services.delete",
  CLASSES_READ: "classes.read",
  CLASSES_CREATE: "classes.create",
  CLASSES_UPDATE: "classes.update",
  CLASSES_DELETE: "classes.delete",
  STAGES_READ: "stages.read",
  STAGES_CREATE: "stages.create",
  STAGES_UPDATE: "stages.update",
  STAGES_DELETE: "stages.delete",
  SPIRITUAL_READ: "spiritual.read",
  SPIRITUAL_CREATE: "spiritual.create",
  TENANTS_READ: "tenants.read",
  TENANTS_CREATE: "tenants.create",
  TENANTS_UPDATE: "tenants.update",
  TENANTS_DELETE: "tenants.delete",
  USERS_READ: "users.read",
  USERS_UPDATE: "users.update",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",
  IMPORT_EXECUTE: "import.execute",
  EXPORT_EXECUTE: "export.execute",
  AUDIT_READ: "audit.read",
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",
  BILLING_READ: "billing.read",
  SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
  SUPPORT_MANAGE: "support.manage",
  SYSTEM_AUDIT: "system.audit",
  SYSTEM_METRICS: "system.metrics",
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const PERMISSION_LIST = Object.values(PERMISSION_CODES) as PermissionCode[];
